"""Build semantic static pages. Run: python3 build.py. No dependencies required."""
from pathlib import Path
from urllib.parse import quote
from html import escape as esc
import json,os
from seo import metadata
ROOT=Path(__file__).resolve().parent
cats=json.loads((ROOT/'src/catalogue.json').read_text())
products=json.loads((ROOT/'src/products.json').read_text())
for product in products:
 if product['categorySlug'] not in {c['slug'] for c in cats}:
  raise ValueError('Unknown product category: '+product['categorySlug'])
config=json.loads((ROOT/'src/site.json').read_text())
config['site_url']=os.environ.get('SITE_URL',config['site_url']).rstrip('/')
BASE=config['site_url']
WA=config['whatsapp']
phone='tel:'+config['phone']
mail=config['email']
def wa(context='garden supplies'):
 return 'https://wa.me/'+WA+'?text='+quote(f'Hi Evergreen, I would like to enquire about {context}.\n\nQuantity / area: \nDelivery postcode (or collection): \nDetails: ')
def button(label,href,kind='primary'):
 return f'<a class="button {kind}" href="{esc(href)}">{label}<span aria-hidden="true">↗</span></a>'
def img(name,alt,hero=False):
 widths=[480,960,1600] if name in ['hero','nursery'] else [480,960]
 return f'<img src="/assets/{name}-960.webp" srcset="'+', '.join(f'/assets/{name}-{w}.webp {w}w' for w in widths)+f'" sizes="{("100vw" if hero else "(min-width: 900px) 45vw, 100vw")}" alt="{esc(alt)}" width="960" height="720" '+('fetchpriority="high"' if hero else 'loading="lazy"')+' decoding="async">'
def header():
 return f'''<a class="skip" href="#main">Skip to content</a><div class="topline"><span>Visit & collect at Mott Street Nursery, E4 7RW</span><span>Delivery around the M25</span></div><header class="header wrap"><a class="brand" href="/" aria-label="Evergreen Garden Supplies home"><img src="/assets/logo.webp" width="264" height="82" alt="Evergreen Garden Supplies Ltd"></a><nav aria-label="Main navigation"><a href="/#products">Products</a><a href="/#delivery">Delivery & collection</a><a href="/#visit">Visit us</a></nav><a class="header-phone" href="{phone}">01992 716222</a><button class="menu-toggle" hidden aria-expanded="false" aria-controls="mobile-menu">Menu <span aria-hidden="true">☰</span></button></header><nav id="mobile-menu" class="mobile-menu" aria-label="Mobile navigation" hidden><a href="/#products">Browse products</a><a href="/#delivery">Delivery & collection</a><a href="/#trade">Homeowners & trade</a><a href="/#visit">Visit & contact</a></nav><noscript><nav class="nojs-nav wrap" aria-label="Navigation"><a href="/#products">Products</a><a href="/#delivery">Delivery</a><a href="/#visit">Visit us</a></nav></noscript>'''
def finalcta(context='garden supplies'):
 return f'''<section class="final-cta"><div class="wrap final-inner"><div><p class="eyebrow">PRICES, AVAILABILITY & DELIVERY</p><h2>Ask us for a quote.</h2><p>Send your materials list, quantities and delivery postcode.</p></div><div class="final-actions">{button('Enquire on WhatsApp',wa(context),'light')}<a href="{phone}">Or call 01992 716222</a></div></div></section>'''
def footer(context='garden supplies'):
 return f'''<footer class="wrap"><div class="footer-main"><a href="/" aria-label="Evergreen home"><img src="/assets/logo.webp" width="230" height="72" alt="Evergreen Garden Supplies Ltd" loading="lazy"></a><p>Mott Street Nursery<br>Mott Street, E4 7RW</p><div><a href="{phone}">01992 716222</a><br><a href="mailto:{mail}">{mail}</a></div></div><div class="footer-small"><span>© Evergreen Garden Supplies Ltd</span><span>Homeowners & trade welcome</span><a href="/privacy/">Privacy</a></div></footer><div class="mobile-actions" aria-label="Quick contact">{button('WhatsApp',wa(context))}<a class="button outline" href="{phone}">Call us</a></div><script src="/site.js" defer></script>'''
def shell(title,desc,body,path='/',context='garden supplies',schema=None):
 full_title=title+' | Evergreen Garden Supplies'
 head=metadata(config,full_title,desc,path,schema)
 html=f'''<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{esc(full_title)}</title>{head}<link rel="icon" href="/assets/logo.webp"><link rel="stylesheet" href="/styles.css"></head><body>{header()}<main id="main">{body}</main>{footer(context)}</body></html>'''
 dest=ROOT/path.strip('/') if path.endswith('.html') else ROOT/path.strip('/')/'index.html'
 dest.parent.mkdir(parents=True,exist_ok=True)
 dest.write_text(html)

def categorycard(c,i):
 return f'''<a class="category" href="/products/{c['slug']}/">{img(c['image'],c['alt'])}<div class="category-label"><span class="number">0{i}</span><h3>{esc(c['name'])}</h3><span class="arrow" aria-hidden="true">↗</span></div></a>'''
features=[('topiary','Topiary & statement plants','Plants & Trees','plants-trees','Sculptural potted topiary photographed at the Evergreen yard'),('compost','Multipurpose compost','Soil & Compost','soil-compost','Evergreen multipurpose compost bag'),('aggregates','Decorative aggregates','Aggregates','aggregates','Decorative stone in a bulk bag at Evergreen')]
def featurecard(f):
 image,title,category,slug,alt=f
 return f'''<article class="feature">{img(image,alt)}<p class="eyebrow">{esc(category)}</p><h3><a href="/products/{slug}/">{esc(title)}</a></h3><p>Enquire for price</p><a class="text-link" aria-label="Ask on WhatsApp about {esc(title)}" href="{esc(wa(title))}">Ask on WhatsApp <span aria-hidden="true">↗</span></a></article>'''
home=f'''<section class="hero wrap"><div class="hero-panel"><div><p class="eyebrow">MOTT STREET NURSERY · E4 7RW</p><h1>Garden &<br>landscaping supplies.</h1></div><div class="hero-intro"><p>Plants and trees, soil, stone and materials for the garden.<br>Visit the nursery, collect from the yard or ask about delivery.</p><a class="text-link" href="/#products">Browse the ranges <span aria-hidden="true">↓</span></a></div></div>{img('hero','Rows of trees beside the paved walkway at Evergreen Garden Supplies',True)}<div class="photo-credit">At our Mott Street nursery</div></section>
<div class="service-strip wrap"><span>Plants to paving</span><span>Visit & collect</span><span>Delivery around the M25</span></div>
<section class="section wrap" id="products"><div class="section-head"><div><p class="eyebrow">GARDEN & LANDSCAPING</p><h2>Our ranges</h2></div><p>Choose a range to enquire about prices and current availability.</p></div><div class="categories">{''.join(categorycard(c,i+1) for i,c in enumerate(cats))}</div><p class="range-note">Photos show our ranges, not live stock or prices. Please confirm current prices and availability before you travel.</p></section>
<section class="delivery section" id="delivery"><div class="wrap split"><div class="delivery-photo">{img('lorry','Evergreen delivery lorry parked at Mott Street Nursery')}<span class="image-caption">THE EVERGREEN YARD</span></div><div class="delivery-copy"><p class="eyebrow">DELIVERY & COLLECTION</p><h2>Delivery or collection</h2><p>Pick up from Mott Street Nursery, or speak to us about delivery around the M25.</p><div class="numbered"><span>01</span><div><h3>Send us your list</h3><p>What you need, how much and your postcode.</p></div></div><div class="numbered"><span>02</span><div><h3>We’ll confirm the details</h3><p>Availability, price and delivery or collection arrangements.</p></div></div>{button('Ask about delivery',wa('delivery'))}<p class="small">Delivery is confirmed individually. Let us know about any access restrictions.</p></div></div></section>
<section class="section wrap" id="featured"><div class="section-head"><div><p class="eyebrow">FROM THE NURSERY & YARD</p><h2>A selection from our ranges</h2></div><p>A selection from our real yard photographs.<br>Ask the team what’s available today.</p></div><div class="features">{''.join(featurecard(f) for f in features)}</div></section>
<section class="trade wrap" id="trade"><div><p class="eyebrow">HOMEOWNERS & TRADE</p><h2>For your garden.<br>For your customers.</h2></div><div><p>Refreshing your own garden or working on a customer’s? Send us your materials list, including quantities and any sizes you have in mind.</p><a class="text-link" href="{esc(wa('supplies for my garden or landscaping project'))}">Talk to us about your project <span aria-hidden="true">↗</span></a></div></section>
<section class="yard section wrap" id="yard"><div class="yard-media">{img('nursery','Rows of potted plants and topiary at Evergreen nursery')}<p class="image-caption">PLANTS AT OUR MOTT STREET NURSERY</p></div><div class="yard-copy"><p class="eyebrow">MOTT STREET NURSERY</p><h2>Around the yard</h2><p>There’s nothing quite like seeing it for yourself. Browse the plants, take a look at the materials and talk through your plans with us.</p><a class="text-link" href="/#visit">Plan your visit <span aria-hidden="true">↗</span></a></div></section>
<section class="reviews section" id="reviews"><div class="wrap"><div class="section-head"><div><p class="eyebrow">CUSTOMER REVIEWS</p><h2>From customers of the nursery</h2></div><a class="text-link" href="https://maps.google.com/?cid=11117923362961783136">Find Evergreen on Google Maps <span aria-hidden="true">↗</span></a></div><div class="review-grid"><figure><blockquote>“Really helpful, plants in great condition”</blockquote><figcaption><strong>Alison Tye</strong><time datetime="2022-04-18">18/04/2022</time><a href="https://absolutelandscapes.org/local/business/mott-street-nursery-286929">Read review source ↗</a></figcaption></figure><figure><blockquote>“Really happy with the service and friendly staff.”</blockquote><figcaption><strong>Michael Hamilton</strong><time datetime="2021-02-28">28/02/2021</time><a href="https://absolutelandscapes.org/local/business/mott-street-nursery-286929">Read review source ↗</a></figcaption></figure></div><p class="small">Selected excerpts from Google reviews reproduced in the Mott Street Nursery directory listing. Dates shown are the original review dates.</p></div></section>
<section class="section wrap visit" id="visit"><div><p class="eyebrow">FIND US AT MOTT STREET</p><h2>Visit Evergreen</h2><address>Mott Street Nursery<br>Mott Street, E4 7RW</address>{button('Get directions','https://www.google.com/maps/search/?api=1&query=Evergreen+Garden+Supplies+Mott+Street+Nursery+E4+7RW','outline')}<p class="small">Opens Google Maps</p></div><div class="visit-details"><h3>Opening hours</h3><dl class="hours"><div><dt>Monday – Friday</dt><dd>08:00 – 17:00</dd></div><div><dt>Saturday</dt><dd>08:00 – 13:00</dd></div><div><dt>Sunday</dt><dd>Closed</dd></div></dl><div class="contact-links"><a href="{phone}">01992 716222 <span aria-hidden="true">↗</span></a><a href="mailto:{mail}">{mail} <span aria-hidden="true">↗</span></a></div></div></section>{finalcta()}'''
shell('Garden & landscaping supplies in E4','Plants, trees, soil, aggregates and landscaping supplies at Mott Street Nursery, E4 7RW. Visit, collect or enquire about delivery around the M25.',home)
for c in cats + products:
 context=c['name']
 photo=c.get('supporting_photo')
 supporting=(f'<figure class="supporting-photo">{img(photo["image"],photo["alt"])}<figcaption>{esc(photo["caption"])} · Contact us for current availability.</figcaption></figure>' if photo else '')
 product_links=''.join('<li><a href="/products/'+p['categorySlug']+'/'+p['slug']+'/">'+esc(p['name'])+' — Enquire for price</a></li>' for p in products if p['categorySlug']==c['slug'])
 body=f'''<div class="wrap breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="/#products">Products</a><span aria-hidden="true">/</span><span>{esc(context)}</span></div><section class="wrap category-hero"><div><p class="eyebrow">THE EVERGREEN RANGES</p><h1>{esc(context)}</h1><p class="lead">{esc(c['intro'])}</p><p class="availability">Enquire for price <span>·</span> Contact us for current availability.</p>{button('Enquire on WhatsApp',wa(context))}<p class="small">Include your quantity and delivery postcode, or let us know you’ll collect.</p></div>{img(c['image'],c['alt'],True)}</section><section class="section wrap category-detail"><div><p class="eyebrow">LET’S FIND WHAT YOU NEED</p><h2>Talk to us about…</h2><ul class="range-list">{product_links}{''.join('<li>'+esc(x)+'</li>' for x in c['range'])}</ul><p>Our range and stock change. Photos show items photographed at Evergreen and do not confirm current availability.</p><a class="text-link" href="/#visit">Visit the nursery <span aria-hidden="true">↗</span></a>{supporting}</div><div class="enquiry-box"><h2 id="enquiry-heading">Make an enquiry</h2><p>A few details help us give you a useful reply.</p><form hidden aria-labelledby="enquiry-heading" data-enquiry data-category="{esc(context)}"><label for="detail">{esc(c['prompt'])}</label><textarea id="detail" name="details" rows="2" placeholder="Tell us what you’re looking for" maxlength="1500"></textarea><label for="quantity">Quantity or area</label><input id="quantity" name="quantity" placeholder="e.g. 6 bags or 20 m²" maxlength="150"><label for="method">How would you like to receive it?</label><select id="method" name="method"><option>Delivery</option><option>Collection</option><option>Not sure yet</option></select><label for="postcode">Delivery postcode <span>(if applicable)</span></label><input id="postcode" name="postcode" autocomplete="postal-code" maxlength="12" placeholder="e.g. E4 7RW"><button class="button primary" type="submit">Continue to WhatsApp <span aria-hidden="true">↗</span></button><p class="small">Opens WhatsApp with your enquiry ready to send. Nothing is sent until you choose to send it.</p><noscript><p>Use the WhatsApp link above, or call us, to make your enquiry.</p></noscript></form><div class="enquiry-alternatives"><a href="{phone}">Call 01992 716222</a><a href="mailto:{mail}?subject={quote(context+' enquiry')}">Enquire by email ↗</a></div></div></section><section class="section wrap related"><p class="eyebrow">KEEP EXPLORING</p><h2>For the rest of your project.</h2><div class="related-links">{''.join('<a href="/products/'+other['slug']+'/">'+esc(other['name'])+' <span aria-hidden="true">↗</span></a>' for other in cats if other!=c)}</div></section>{finalcta(context)}'''
 schema={'@context':'https://schema.org','@type':('WebPage' if 'categorySlug' in c else 'CollectionPage'),'name':context+' | Evergreen Garden Supplies','description':c['intro']}
 shell(context,c.get('meta_description',context+' at Evergreen, Mott Street Nursery, E4 7RW. Ask for current prices, availability, collection and delivery around the M25.'),body,'/products/'+(c['categorySlug']+'/' if 'categorySlug' in c else '')+c['slug']+'/',context,schema)
shell('Privacy','How enquiries through this website work.',f'''<section class="section wrap prose"><p class="eyebrow">EVERGREEN GARDEN SUPPLIES LTD</p><h1>Privacy & enquiries</h1><p>This website lets you contact Evergreen by telephone, email or WhatsApp. The enquiry form prepares a message on your device; it does not submit information to this website or store your form entries.</p><h2>Contacting us</h2><p>When you send an enquiry, Evergreen receives the information you choose to share, such as your message, contact details and delivery postcode, to respond to your request and discuss supply or delivery.</p><h2>Other services</h2><p>WhatsApp and Google Maps links open services with their own privacy policies. This website uses no analytics scripts, advertising cookies or embedded third-party maps. Hosting services may process standard request logs to serve the site.</p><h2>Questions about your information</h2><p>Contact <a href="mailto:{mail}">{mail}</a> or write to Evergreen Garden Supplies Ltd, Mott Street Nursery, Mott Street, E4 7RW.</p></section>''','/privacy/')
shell('Page not found','Find your way back to Evergreen Garden Supplies.',f'<section class="section wrap prose"><p class="eyebrow">PAGE NOT FOUND</p><h1>Let’s get you back<br>to the garden.</h1><p>This page could not be found.</p>{button("Browse our ranges","/#products")}</section>','/404.html')

if BASE:
 paths=['/','/privacy/']+['/products/'+c['slug']+'/' for c in cats]+['/products/'+p['categorySlug']+'/'+p['slug']+'/' for p in products]
 (ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+esc(BASE+p)+'</loc></url>' for p in paths)+'</urlset>')
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /src/\n'+('Sitemap: '+BASE+'/sitemap.xml\n' if BASE else ''))
print('Built homepage, six categories, privacy and 404. '+('Canonical URLs and sitemap generated.' if BASE else 'Set SITE_URL for canonical URLs and sitemap before launch.'))
