"""Build semantic static pages. Run: python3 build.py. No dependencies required."""
from pathlib import Path
from urllib.parse import quote
from html import escape as esc
import json,os
from seo import metadata
ROOT=Path(__file__).resolve().parent
cats=json.loads((ROOT/'src/catalogue.json').read_text())
products=json.loads((ROOT/'src/products.json').read_text())
for product in products:
 if product['categorySlug'] not in {c['slug'] for c in cats}:
  raise ValueError('Unknown product category: '+product['categorySlug'])
config=json.loads((ROOT/'src/site.json').read_text())
config['site_url']=os.environ.get('SITE_URL',config['site_url']).rstrip('/')
BASE=config['site_url']
WA=config['whatsapp']
phone='tel:'+config['phone']
mail=config['email']
def wa(context='garden supplies'):
 return 'https://wa.me/'+WA+'?text='+quote(f'Hi Evergreen, I would like to enquire about {context}.\n\nQuantity / area: \nDelivery postcode (or collection): \nDetails: ')
NUMWORDS={1:'one',2:'two',3:'three',4:'four',5:'five',6:'six',7:'seven',8:'eight',9:'nine',10:'ten'}
def button(label,href,kind='primary',arrow=True):
 return f'<a class="button {kind}" href="{esc(href)}">{label}'+('<span aria-hidden="true">↗</span>' if arrow else '')+'</a>'
def img(name,alt,hero=False):
 widths=[480,960,1600] if name in ['hero','nursery'] else [480,960]
 return f'<img src="/assets/{name}-960.webp" srcset="'+', '.join(f'/assets/{name}-{w}.webp {w}w' for w in widths)+f'" sizes="{("100vw" if hero else "(min-width: 900px) 45vw, 100vw")}" alt="{esc(alt)}" width="960" height="720" '+('fetchpriority="high"' if hero else 'loading="lazy"')+' decoding="async">'
def header():
 return f'''<a class="skip" href="#main">Skip to content</a><div class="topline"><span>Visit & collect at Mott Street Nursery, E4 7RW</span><span>Delivery around the M25</span></div><header class="header wrap"><a class="brand" href="/" aria-label="Evergreen Garden Supplies home"><img src="/assets/logo.webp" width="264" height="82" alt="Evergreen Garden Supplies Ltd"></a><nav aria-label="Main navigation"><a href="/#products">Products</a><a href="/#delivery">Delivery & collection</a><a href="/#visit">Visit us</a></nav><a class="header-phone" href="{phone}">01992 716222</a><button class="menu-toggle" hidden aria-expanded="false" aria-controls="mobile-menu">Menu <span aria-hidden="true">☰</span></button></header><nav id="mobile-menu" class="mobile-menu" aria-label="Mobile navigation" hidden><a href="/#products">Browse products</a><a href="/#delivery">Delivery & collection</a><a href="/#trade">Homeowners & trade</a><a href="/#visit">Visit & contact</a></nav><noscript><nav class="nojs-nav wrap" aria-label="Navigation"><a href="/#products">Products</a><a href="/#delivery">Delivery</a><a href="/#visit">Visit us</a></nav></noscript>'''
def finalcta(context='garden supplies'):
 return f'''<section class="final-cta"><div class="wrap final-inner"><div><h2>Tell us what you need</h2><p>Quantities, sizes and your postcode — or just say you’ll collect. We’ll come back with a price.</p></div><div class="final-actions">{button('Enquire on WhatsApp',wa(context),'light')}<a href="{phone}">Or call 01992 716222</a></div></div></section>'''
def footer(context='garden supplies'):
 return f'''<footer class="wrap"><div class="footer-main"><a href="/" aria-label="Evergreen home"><img src="/assets/logo.webp" width="230" height="72" alt="Evergreen Garden Supplies Ltd" loading="lazy"></a><p>Mott Street Nursery<br>Mott Street, E4 7RW</p><div><a href="{phone}">01992 716222</a><br><a href="mailto:{mail}">{mail}</a></div></div><div class="footer-small"><span>© Evergreen Garden Supplies Ltd</span><span>Mon–Fri 8–5 · Sat 8–1</span><a href="/privacy/">Privacy</a></div></footer><div class="mobile-actions" aria-label="Quick contact">{button('WhatsApp',wa(context),'primary',False)}<a class="button outline" href="{phone}">Call us</a></div><script src="/site.js" defer></script>'''
def shell(title,desc,body,path='/',context='garden supplies',schema=None):
 full_title=title+' | Evergreen Garden Supplies'
 head=metadata(config,full_title,desc,path,schema)
 html=f'''<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{esc(full_title)}</title>{head}<link rel="preload" href="/assets/fonts/newsreader.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/fonts/source-sans-3.woff2" as="font" type="font/woff2" crossorigin><link rel="icon" href="/assets/logo.webp"><link rel="stylesheet" href="/styles.css"></head><body>{header()}<main id="main">{body}</main>{footer(context)}</body></html>'''
 dest=ROOT/path.strip('/') if path.endswith('.html') else ROOT/path.strip('/')/'index.html'
 dest.parent.mkdir(parents=True,exist_ok=True)
 dest.write_text(html)

def categorycard(c,i):
 return f'''<a class="category" href="/products/{c['slug']}/"><span class="frame">{img(c['image'],c['alt'])}</span><div class="category-label"><span class="number">0{i}</span><h3>{esc(c['name'])}</h3><span class="arrow" aria-hidden="true">→</span></div></a>'''
features=[('topiary','Topiary & statement plants','Plants & Trees','plants-trees','Sculptural potted topiary photographed at the Evergreen yard'),('compost','Multipurpose compost','Soil & Compost','soil-compost','Evergreen multipurpose compost bag'),('aggregates','Decorative aggregates','Aggregates','aggregates','Decorative stone in a bulk bag at Evergreen')]
def featurecard(f):
 image,title,category,slug,alt=f
 return f'''<article class="feature"><span class="frame">{img(image,alt)}</span><p class="eyebrow">{esc(category)}</p><h3><a href="/products/{slug}/">{esc(title)}</a></h3><a class="text-link" aria-label="Ask on WhatsApp about {esc(title)}" href="{esc(wa(title))}">Ask on WhatsApp <span aria-hidden="true">↗</span></a></article>'''
home=f'''<section class="hero wrap"><div class="hero-panel"><div><p class="eyebrow">Mott Street Nursery · E4 7RW</p><h1>Everything for the garden, <br class="desktop-break">from our yard on Mott Street</h1></div><div class="hero-intro"><p>A working nursery and yard in E4. Plants and trees, soil and compost, stone, turf, paving and timber. Come and load up, or send us a list and we’ll deliver.</p><a class="text-link" href="/#products">Browse the ranges <span aria-hidden="true">↓</span></a></div></div>{img('hero','Rows of trees beside the paved walkway at Evergreen Garden Supplies',True)}<div class="photo-credit">At our Mott Street nursery</div></section>
<div class="service-strip wrap"><span>Plants, soil, stone &amp; paving</span><span>Visit &amp; collect</span><span>Delivery around the M25</span></div>
<section class="section wrap" id="products"><div class="section-head"><div><h2>Our ranges</h2></div><p>Everything we keep at the yard, grouped into {NUMWORDS.get(len(cats),len(cats))} ranges. Ask us what’s in and we’ll price it up.</p></div><div class="categories">{''.join(categorycard(c,i+1) for i,c in enumerate(cats))}</div><p class="range-note">Photos show the kind of thing we keep, not today’s stock. Ring before you travel and we’ll tell you what’s in.</p></section>
<section class="delivery section" id="delivery"><div class="wrap split"><div class="delivery-photo">{img('lorry','Evergreen delivery lorry parked at Mott Street Nursery')}<span class="image-caption">THE EVERGREEN YARD</span></div><div class="delivery-copy"><h2>Delivery or collection</h2><p>Load up at the yard on Mott Street, or we’ll run it out to you around the M25.</p><p>Send us what you need, how much of it, and your postcode. We’ll come back with a price, what we’ve got in, and when we can get it to you.</p>{button('Ask about delivery',wa('delivery'))}<p class="small">Tell us about anything tight — narrow lanes, low bridges, awkward parking — so we send the right vehicle.</p></div></div></section>
<section class="section wrap" id="featured"><div class="section-head"><div><h2>A few things we keep</h2></div><p>All photographed at our own yard. Ask us what’s in today.</p></div><div class="features">{''.join(featurecard(f) for f in features)}</div></section>
<section class="trade wrap" id="trade"><div><h2>Whether it’s your garden <br class="desktop-break">or your customer’s</h2></div><div><p>Send over a materials list with quantities and sizes and we’ll price it up — one bag or a full load.</p><a class="text-link" href="{esc(wa('supplies for my garden or landscaping project'))}">Send us your list <span aria-hidden="true">↗</span></a></div></section>
<section class="yard section wrap" id="yard"><div class="yard-media">{img('nursery','Rows of potted plants and topiary at Evergreen nursery')}<p class="image-caption">PLANTS AT OUR MOTT STREET NURSERY</p></div><div class="yard-copy"><h2>Come and have a look</h2><p>Walk the rows, see the actual plant you’re buying, get your hands in the compost. Bring your measurements and we’ll work out quantities with you.</p><a class="text-link" href="/#visit">Where to find us</a></div></section>
<section class="reviews section" id="reviews"><div class="wrap"><div class="section-head"><div><h2>From customers of the nursery</h2></div><a class="text-link" href="https://maps.google.com/?cid=11117923362961783136">Find Evergreen on Google Maps <span aria-hidden="true">↗</span></a></div><div class="review-grid"><figure><blockquote>“Really helpful, plants in great condition”</blockquote><figcaption><strong>Alison Tye</strong><time datetime="2022-04-18">18/04/2022</time><a href="https://absolutelandscapes.org/local/business/mott-street-nursery-286929">Read review source ↗</a></figcaption></figure><figure><blockquote>“Really happy with the service and friendly staff.”</blockquote><figcaption><strong>Michael Hamilton</strong><time datetime="2021-02-28">28/02/2021</time><a href="https://absolutelandscapes.org/local/business/mott-street-nursery-286929">Read review source ↗</a></figcaption></figure></div><p class="small">Selected excerpts from Google reviews reproduced in the Mott Street Nursery directory listing. Dates shown are the original review dates.</p></div></section>
<section class="section wrap visit" id="visit"><div><h2>Visit Evergreen</h2><address>Mott Street Nursery<br>Mott Street, E4 7RW</address>{button('Get directions','https://www.google.com/maps/search/?api=1&query=Evergreen+Garden+Supplies+Mott+Street+Nursery+E4+7RW','outline')}<p class="small">Opens Google Maps</p></div><div class="visit-details"><h3>Opening hours</h3><dl class="hours"><div><dt>Monday – Friday</dt><dd>08:00 – 17:00</dd></div><div><dt>Saturday</dt><dd>08:00 – 13:00</dd></div><div><dt>Sunday</dt><dd>Closed</dd></div></dl><div class="contact-links"><a href="{phone}">01992 716222 <span aria-hidden="true">↗</span></a><a href="mailto:{mail}">{mail} <span aria-hidden="true">↗</span></a></div></div></section>{finalcta()}'''
shell('Garden & landscaping supplies in E4','Plants, trees, soil, aggregates and landscaping supplies at Mott Street Nursery, E4 7RW. Visit, collect or enquire about delivery around the M25.',home)
for c in cats + products:
 context=c['name']
 photo=c.get('supporting_photo')
 supporting=(f'<figure class="supporting-photo">{img(photo["image"],photo["alt"])}<figcaption>{esc(photo["caption"])}</figcaption></figure>' if photo else '')
 product_links=''.join('<li><a href="/products/'+p['categorySlug']+'/'+p['slug']+'/">'+esc(p['name'])+' — Enquire for price</a></li>' for p in products if p['categorySlug']==c['slug'])
 body=f'''<div class="wrap breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><a href="/#products">Products</a><span aria-hidden="true">/</span><span>{esc(context)}</span></div><section class="wrap category-hero"><div><h1>{esc(context)}</h1><p class="lead">{esc(c['intro'])}</p>{button('Enquire on WhatsApp',wa(context))}<p class="small">Tell us how much you need and your postcode — or that you’ll collect.</p></div>{img(c['image'],c['alt'],True)}</section><section class="section wrap category-detail"><div><h2>In this range</h2><ul class="range-list">{product_links}{''.join('<li>'+esc(x)+'</li>' for x in c['range'])}</ul><p>Photos are from our own yard. Ring and we’ll tell you what’s in today.</p><a class="text-link" href="/#visit">Visit the nursery</a>{supporting}</div><div class="enquiry-box"><h2 id="enquiry-heading">Make an enquiry</h2><p>A few details and we can give you a proper price.</p><form hidden aria-labelledby="enquiry-heading" data-enquiry data-category="{esc(context)}"><label for="detail">{esc(c['prompt'])}</label><textarea id="detail" name="details" rows="2" placeholder="Tell us what you’re looking for" maxlength="1500"></textarea><label for="quantity">Quantity or area</label><input id="quantity" name="quantity" placeholder="e.g. 6 bags or 20 m²" maxlength="150"><label for="method">How would you like to receive it?</label><select id="method" name="method"><option>Delivery</option><option>Collection</option><option>Not sure yet</option></select><label for="postcode">Delivery postcode <span>(if applicable)</span></label><input id="postcode" name="postcode" autocomplete="postal-code" maxlength="12" placeholder="e.g. E4 7RW"><button class="button primary" type="submit">Continue to WhatsApp <span aria-hidden="true">↗</span></button><p class="small">Opens WhatsApp with your enquiry ready to send. Nothing is sent until you choose to send it.</p><noscript><p>Use the WhatsApp link above, or call us, to make your enquiry.</p></noscript></form><div class="enquiry-alternatives"><a href="{phone}">Call 01992 716222</a><a href="mailto:{mail}?subject={quote(context+' enquiry')}">Enquire by email ↗</a></div></div></section><section class="section wrap related"><h2>Other ranges</h2><div class="related-links">{''.join('<a href="/products/'+other['slug']+'/">'+esc(other['name'])+'</a>' for other in cats if other!=c)}</div></section>{finalcta(context)}'''
 schema={'@context':'https://schema.org','@type':('WebPage' if 'categorySlug' in c else 'CollectionPage'),'name':context+' | Evergreen Garden Supplies','description':c['intro']}
 shell(context,c.get('meta_description',context+' at Evergreen, Mott Street Nursery, E4 7RW. Ask for current prices, availability, collection and delivery around the M25.'),body,'/products/'+(c['categorySlug']+'/' if 'categorySlug' in c else '')+c['slug']+'/',context,schema)
shell('Privacy','How enquiries through this website work.',f'''<section class="section wrap prose"><h1>Privacy &amp; enquiries</h1><p>This website lets you contact Evergreen by telephone, email or WhatsApp. The enquiry form prepares a message on your device; it does not submit information to this website or store your form entries.</p><h2>Contacting us</h2><p>When you send an enquiry, Evergreen receives the information you choose to share, such as your message, contact details and delivery postcode, to respond to your request and discuss supply or delivery.</p><h2>Other services</h2><p>WhatsApp and Google Maps links open services with their own privacy policies. This website uses no analytics scripts, advertising cookies or embedded third-party maps. Hosting services may process standard request logs to serve the site.</p><h2>Questions about your information</h2><p>Contact <a href="mailto:{mail}">{mail}</a> or write to Evergreen Garden Supplies Ltd, Mott Street Nursery, Mott Street, E4 7RW.</p></section>''','/privacy/')
shell('Page not found','Find your way back to Evergreen Garden Supplies.',f'<section class="section wrap prose"><h1>We can’t find that page</h1><p>It may have moved, or the link may be wrong. Try the ranges below, or give us a ring on 01992 716222.</p>{button("Browse our ranges","/#products","primary",False)}</section>','/404.html')

if BASE:
 paths=['/','/privacy/']+['/products/'+c['slug']+'/' for c in cats]+['/products/'+p['categorySlug']+'/'+p['slug']+'/' for p in products]
 (ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+esc(BASE+p)+'</loc></url>' for p in paths)+'</urlset>')
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /src/\n'+('Sitemap: '+BASE+'/sitemap.xml\n' if BASE else ''))
print('Built homepage, six categories, privacy and 404. '+('Canonical URLs and sitemap generated.' if BASE else 'Set SITE_URL for canonical URLs and sitemap before launch.'))
